#!/bin/bash
CONFIG_FILE=$PWD/config.conf
if [ ! -f $CONFIG_FILE ]
then
    echo '********************************************'
    echo '* can not load config file :'$CONFIG_FILE
    echo '********************************************'
    exit
fi
. $CONFIG_FILE

ARGUMENTS=''
while [ "$1" != "" ]; do
  ARGUMENTS=$ARGUMENTS" ${1}" 
	shift;
done;
docker exec -it $WEB_CONTAINER_NAME su - app -c "cd $SITE_ROOT/ && composer $ARGUMENTS"

